{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "heyteago-diy.fullname" . }}
  labels:
    {{- include "heyteago-diy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "heyteago-diy.fullname" $ }}-server
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "heyteago-diy.fullname" $ }}-web
                port:
                  name: http
    {{- end }}
{{- end }}
