apiVersion: v1
kind: Service
metadata:
  name: {{ include "heyteago-diy.fullname" . }}-web
  labels:
    {{- include "heyteago-diy.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    {{- include "heyteago-diy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
